version: '3.3'
services:
    front:
        build:
            context: ./
            dockerfile: Dockerfile.prod
        container_name: RadioWidget
        security_opt:
            - apparmor:unconfined
        restart: always
        ports:
            - '3000:3000'
        command: bash -c "yarn build && serve -s build -p 3000"
