name: learn-github-actions
on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - run: git pull origin master
            - run: sudo docker-compose -f docker-compose.prod.yml up --build -d
            - run: sudo docker image prune --force
            - run: sudo docker system prune --force
